Harden: Normalize shell dependency loading boilerplate
- REFER:

  https://github.com/DepoXy/sh-source-deps-template#🤞

diff --git a/bin/git-rebase-tip b/bin/git-rebase-tip
--- a/bin/git-rebase-tip
+++ b/bin/git-rebase-tip
@@ -76,37 +76,117 @@
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
-source_deps () {
+# *** <beg boilerplate `source_deps`: ------------------------------|
+#                                                                   |
+
+_git_rebase_tip__this_filename="git-rebase-tip"
+
+_git_rebase_tip__source_deps () {
+  local sourced_all=true
+
+  # On Bash, user can source this file from anywhere.
+  # - If not Bash, user must `cd` to this file's parent directory first.
+  local prefix="$(dirname -- "${_git_rebase_tip__this_fullpath}")"
+
+  # USAGE: Load dependencies using path relative to this file, e.g.:
+  #   _source_file "${prefix}" "../deps/path/to/lib" "dependency.sh"
+
+  #                                                                 |
+  # *** stop boilerplate> ------------------------------------------|
+
   # Runs: _grtcommon_source_deps
-  source_lib \
-    "${GITREPOSPATH:-${DOPP_KIT:-${HOME}/.kit}/git}/git-rebase-tip" \
-    "lib/git-rebase-tip-common.sh" \
-    || return 1
+  _git_rebase_tip__source_file "${prefix}" "../lib" "git-rebase-tip-common.sh"
+
+  # *** <more boilerplate: -----------------------------------------|
+  #                                                                 |
+
+  ${sourced_all}
 }
 
-# ***
+_git_rebase_tip__smells_like_bash () { declare -p BASH_SOURCE > /dev/null 2>&1; }
 
-# USYNC: Same source_lib in all the files.
-source_lib () {
-  # For DepoXy users, the project parent directory.
-  local depoxy_basedir="$1"
-  # As fallback, check deps/ which ships with this project.
-  local deps_lib_path="$2"
-
-  local lib_name
-  lib_name="$(basename -- "${deps_lib_path}")"
-
-  if . "${depoxy_basedir}/${deps_lib_path}" 2> /dev/null \
-    || . "$(dirname -- "$(realpath -- "$0")")/../deps/${deps_lib_path}" \
-  ; then
-
-    return 0
+_git_rebase_tip__print_this_fullpath () {
+  if _git_rebase_tip__smells_like_bash; then
+    echo "$(realpath -- "${BASH_SOURCE[0]}")"
+  elif [ "$(basename -- "$0")" = "${_git_rebase_tip__this_filename}" ]; then
+    # Assumes this script being executed, and $0 is its path.
+    echo "$(realpath -- "$0")"
+  else
+    # Assumes cwd is this script's parent directory.
+    echo "$(realpath -- "${_git_rebase_tip__this_filename}")"
   fi
-  
-  >&2 echo "ERROR: Cannot determine source path for dependency: ${lib_name}"
-
-  return 1
 }
+
+_git_rebase_tip__this_fullpath="$(_git_rebase_tip__print_this_fullpath)"
+
+_git_rebase_tip__shell_sourced () {
+  [ "$(realpath -- "$0")" != "${_git_rebase_tip__this_fullpath}" ]
+}
+
+_git_rebase_tip__source_file () {
+  local prfx="${1:-.}"
+  local depd="${2:-.}"
+  local file="${3:-.}"
+
+  local deps_dir="${prfx}/${depd}"
+  local deps_path="${deps_dir}/${file}"
+
+  # Just in case sourced file overwrites top-level `_git_rebase_tip__this_filename`,
+  # cache our copy, should we need it for an error message.
+  local _this_file_name="${_git_rebase_tip__this_filename}"
+
+  if [ -f "${deps_path}" ]; then
+    # SAVVY: Source files from their dirs, so they can find their deps.
+    local before_cd="$(pwd -L)"
+    cd "${deps_dir}"
+    # SAVVY: If errexit, error while sourcing kills process immediately,
+    # and error you see might indicate this source file, but the line
+    # number for the file being sourced. E.g.,
+    #   /path/to/bin/myapp: 442: export: Illegal option -f
+    # where `442` is line number from, e.g., 'deps/lib/dep.sh'.
+    if ! . "${deps_path}"; then
+      >&2 echo "ERROR: Dependency ‘${file}’ returned nonzero when sourced"
+      sourced_all=false
+    fi
+    cd "${before_cd}"
+  else
+    local depstxt=""
+    [ "${prfx}" = "." ] || depstxt="in ‘${deps_dir}’ or "
+    >&2 echo "ERROR: ‘${file}’ not found under ‘${deps_dir}’"
+    if _git_rebase_tip__smells_like_bash; then
+      >&2 echo "- GAFFE: This looks like an error with the ‘_git_rebase_tip__source_file’ arguments"
+    else
+      >&2 echo "- HINT: You must source ‘${_this_file_name}’ from its parent directory"
+    fi
+    sourced_all=false
+  fi
+}
+
+# BONUS: You can use these aliases instead of the uniquely-named functions,
+# just be aware not to call any alias after calling _source_deps.
+_shell_sourced () { _git_rebase_tip__shell_sourced; }
+_source_deps () { _git_rebase_tip__source_deps; }
+
+_git_rebase_tip__source_deps_unset_cleanup () {
+  unset -v _git_rebase_tip__this_filename
+  unset -f _git_rebase_tip__print_this_fullpath
+  unset -f _git_rebase_tip__shell_sourced
+  unset -f _shell_sourced
+  unset -f _git_rebase_tip__smells_like_bash
+  unset -f _git_rebase_tip__source_deps
+  unset -f _source_deps
+  unset -f _git_rebase_tip__source_deps_unset_cleanup
+  unset -f _git_rebase_tip__source_file
+}
+
+# USAGE: When this file is being executed, before doing stuff, call:
+#   _source_deps
+# - When this file is being sourced, call both:
+#   _source_deps
+#   _git_rebase_tip__source_deps_unset_cleanup
+
+#                                                                   |
+# *** end boilerplate `source_deps`> -------------------------------|
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
@@ -605,20 +685,19 @@ main () {
 
   set_traps
 
+  _source_deps
+
   rebase_tip "$@"
 
-  # Unhook traps.
   clear_traps
 }
 
-# Ensure coreutils.
-if source_deps; then
-  # Run the command unless being sourced.
-  if [ "$(basename -- "$(realpath -- "$0")")" = "${PROG_NAME}" ]; then
-    main "$@"
-  fi
+if _shell_sourced; then
+  _source_deps
+else
+  main "$@"
 fi
 
+_git_rebase_tip__source_deps_unset_cleanup
 unset -f main
-unset -f source_deps
 
